---
title: Himanshu Goel
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: http://himanshugoel.in
baseurl: ''
description: Welcome!
navbar-links:
  Tags: tags
  Books:
  - Top Books: https://himanshugoel.in/books/
  - Book Notes: https://himanshugoel.in/books/
  Productivity:
  - Top Productivity Apps: https://himanshugoel.in/books/
  - Productivity Articles: https://himanshugoel.in/books/
  Infosec:
  - Certifications: https://himanshugoel.in/books/
  - Compliances: https://himanshugoel.in/books/
  - Infosec Blog: https://himanshugoel.in/books/
  Meditation:
  - Top Meditation Apps: https://himanshugoel.in/books/
  - Meditation Log: https://himanshugoel.in/books/
  - Meditation Notes: https://himanshugoel.in/books/
  Fitness:
  - Top Fitness Apps: https://himanshugoel.in/books/
  - Fitness Log: https://himanshugoel.in/books/
  - Fitness Notes: https://himanshugoel.in/books/
  About Me: aboutme
avatar: "/img/newhg.jpg"
author:
  name: Himanshu Goel
social-network-links:
  github: himanshugoel21
  twitter: himanshugoel21
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
metadata:
  _posts:
  - name: layout
    field:
      element: hidden
      value: post
  - name: title
    field:
      element: text
      label: Post title
      placeholder: Title
      alterable: true
  - name: subtitle
    field:
      element: textarea
      label: Subtitle
      placeholder: A description of your post.
      alterable: true
  - name: date
    field:
      element: text
      label: Date
      help: Enter date of post.
      placeholder: yyyy-mm-dd
      alterable: true
  - name: image
    field:
      element: text
      label: Image
      help: Add a thumbnail image to your post.
      placeholder: Thumbnail
      alterable: true
  - name: published
    field:
      element: checkbox
      label: Publish
      help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
- jemoji
